/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedmyschool.View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import managedmyschool.Controller.ClassMethodes;
import managedmyschool.Controller.HelperMethodes;
import managedmyschool.Controller.StudentsMethodes;
import managedmyschool.Controller.TeachersMethodes;
import managedmyschool.Model.Lesson;
import managedmyschool.Model.Student;

/**
 *
 * @author achrafchennan
 */
public class EditMyStudents extends javax.swing.JFrame {

    ClassMethodes classMethodes;
    StudentsMethodes studentMethodes;
    TeachersMethodes teacherMethodes;
    HelperMethodes helperMethodes;
    List<Student> studentsList;
    List<Lesson> lessonList;
    Boolean columsAreSet;
    Student selectedStudent;
    String loginUser;
    private String[] COLUMNSSTUDENTTABLE = {"Voornaam", "Achternaam"};

    private DefaultTableModel model = new DefaultTableModel(COLUMNSSTUDENTTABLE, 0);

    /**
     * Creates new form EditMyClass
     */
    public EditMyStudents() {
        initComponents();
        this.classMethodes = new ClassMethodes();
        this.studentMethodes = new StudentsMethodes();
        this.teacherMethodes = new TeachersMethodes();
        this.helperMethodes = new HelperMethodes();
        this.columsAreSet = false;
    }

    public EditMyStudents(String loginUser) {
        initComponents();
        this.loginUser = loginUser;
    }

    public void createConstructor() {

        this.classMethodes = new ClassMethodes();
        this.studentMethodes = new StudentsMethodes();
        this.teacherMethodes = new TeachersMethodes();
        this.columsAreSet = false;
        this.lessonList = classMethodes.getClasses();
    }

    public void getStudents(String className) {
        this.studentsList = studentMethodes.getStudentsFromClass(className);
        fillStudentTable();
    }

    public void fillStudentTable() {

        this.tbStudents.setModel(model);
        for (Student student : this.studentsList) {
            Object[] data = {student.getFirstName(), student.getLastName()};
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudents = new javax.swing.JTable(model);
        cbClasses = new javax.swing.JComboBox<>();
        btGoBack = new javax.swing.JButton();
        tbEditStudent = new javax.swing.JButton();
        lbEditStudentTitle = new javax.swing.JLabel();
        lbCurrentClass = new javax.swing.JLabel();
        cbCurrentClass = new javax.swing.JComboBox<>();
        tbFirstName = new javax.swing.JTextField();
        lbFirstName = new javax.swing.JLabel();
        lbMonthleyPay = new javax.swing.JLabel();
        lbChooseClass = new javax.swing.JLabel();
        lbShartNumber = new javax.swing.JLabel();
        lbLastName = new javax.swing.JLabel();
        tbLastName = new javax.swing.JTextField();
        lbPhoneParent = new javax.swing.JLabel();
        tbPhoneParent = new javax.swing.JTextField();
        tbShartNumber = new javax.swing.JTextField();
        tbMonthleyPayment = new javax.swing.JTextField();
        lbLastEditBy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStudents);

        if(this.lessonList == null){
            this.createConstructor();
        }

        cbClasses.addItem("Selecteer een klas");
        for(Lesson les : this.lessonList){
            cbClasses.addItem(les.getClassName());
        }
        cbClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClassesActionPerformed(evt);
            }
        });

        btGoBack.setLabel("Vorige");
        btGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoBackActionPerformed(evt);
            }
        });

        tbEditStudent.setText("Opslaan");
        tbEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditStudentActionPerformed(evt);
            }
        });

        lbEditStudentTitle.setText("Student wijzigen");

        lbCurrentClass.setText("Huidige Klas:");

        cbCurrentClass.addItem("Selecteer een klas");
        for(Lesson les : this.lessonList){
            cbCurrentClass.addItem(les.getClassName());
        }

        tbFirstName.setToolTipText("");

        lbFirstName.setText("Voornaam:");

        lbMonthleyPay.setText("Bijdragen:");

        lbChooseClass.setText("Klas:");

        lbShartNumber.setText("ShartNummer:");

        lbLastName.setText("Achternaam:");

        tbLastName.setToolTipText("");

        lbPhoneParent.setText("Tel. Ouders");

        tbPhoneParent.setToolTipText("");

        tbShartNumber.setToolTipText("");

        tbMonthleyPayment.setToolTipText("");

        lbLastEditBy.setText("Laatst aangepast door");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(tbEditStudent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(lbChooseClass))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbPhoneParent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbPhoneParent, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbFirstName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbLastName)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbMonthleyPay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbMonthleyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbShartNumber)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tbShartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbCurrentClass)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbCurrentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(lbEditStudentTitle)))
                                .addGap(21, 21, 21)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbLastEditBy)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btGoBack)
                    .addContainerGap(765, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbEditStudentTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbChooseClass)
                                    .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCurrentClass)
                                    .addComponent(cbCurrentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMonthleyPay)
                                    .addComponent(tbMonthleyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbPhoneParent, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbPhoneParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbShartNumber)
                                    .addComponent(tbShartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(lbLastEditBy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(tbEditStudent)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(btGoBack)
                    .addGap(33, 33, 33)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentsMouseClicked
        // TODO add your handling code here:
        int row = tbStudents.rowAtPoint(evt.getPoint());

        this.selectedStudent = this.studentsList.get(row);
        this.tbFirstName.setText(selectedStudent.getFirstName());

        this.tbLastName.setText(selectedStudent.getLastName());

        this.tbMonthleyPayment.setText(String.valueOf(selectedStudent.getMonthleyPayment()));
        this.tbPhoneParent.setText(selectedStudent.getPhoneNumberParent());
        this.tbShartNumber.setText(String.valueOf(selectedStudent.getShartNumber()));
    }//GEN-LAST:event_tbStudentsMouseClicked

    private void cbClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClassesActionPerformed
        // TODO add your handling code here:

        //set also the selected class for the second cb
        this.cbCurrentClass.setSelectedItem(this.cbClasses.getSelectedItem().toString());
        this.getStudents(this.cbClasses.getSelectedItem().toString());
    }//GEN-LAST:event_cbClassesActionPerformed

    private void btGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoBackActionPerformed
        MyHome main = new MyHome();
        this.setVisible(false);

        main.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btGoBackActionPerformed

    private void tbEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditStudentActionPerformed
        // TODO add your handling code here:
        String firstName, lastName, phoneNumberParent, classNameNew;
        int monthlyPayment;
        firstName = this.tbFirstName.getText();
        lastName = this.tbLastName.getText();
        phoneNumberParent = this.tbPhoneParent.getText();
        String shart = this.tbShartNumber.getText();
        String monthly = this.tbMonthleyPayment.getText();
        int shartNumber = HelperMethodes.tryParseInt(shart) ? Integer.parseInt(shart) : 0;
        monthlyPayment = HelperMethodes.tryParseInt(monthly) ? Integer.parseInt(monthly) : 0;
        classNameNew = cbCurrentClass.getSelectedItem().toString();

        String resp = this.studentMethodes.updateStudent(selectedStudent.getId(), firstName, lastName, selectedStudent.getBirthDay(), classNameNew, phoneNumberParent, lastName, monthlyPayment, shartNumber);
        JOptionPane.showMessageDialog(null,
                resp,
                "Resultaat",
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_tbEditStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMyStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMyStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMyStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMyStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMyStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGoBack;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JComboBox<String> cbCurrentClass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChooseClass;
    private javax.swing.JLabel lbCurrentClass;
    private javax.swing.JLabel lbEditStudentTitle;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastEditBy;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbMonthleyPay;
    private javax.swing.JLabel lbPhoneParent;
    private javax.swing.JLabel lbShartNumber;
    private javax.swing.JButton tbEditStudent;
    private javax.swing.JTextField tbFirstName;
    private javax.swing.JTextField tbLastName;
    private javax.swing.JTextField tbMonthleyPayment;
    private javax.swing.JTextField tbPhoneParent;
    private javax.swing.JTextField tbShartNumber;
    private javax.swing.JTable tbStudents;
    // End of variables declaration//GEN-END:variables
}
