/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedmyschool.View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import managedmyschool.Controller.*;
import managedmyschool.Model.*;

/**
 *
 * @author achrafchennan
 */
public class StudentsCostPage extends javax.swing.JPanel {

    StudentsMethodes studentsMethodes;
    ClassMethodes classMethodes;
    PaymentMethodes paymentMethodes;
    List<Lesson> lessonList;
    List<Student> studentList;
    Boolean columsAreSet;
    private DefaultTableModel modelSetTable = new DefaultTableModel() {
        public Class<?> getColumnClass(int column) {
            switch (column) {
                case 0:
                    return int.class;
                case 1:
                    return int.class;
                case 2:
                    return String.class;
                default:
                    return String.class;
            }
        }

    };

    /**
     * Creates new form EditStudents
     */
    public StudentsCostPage() {
        initComponents();
        studentsMethodes = new StudentsMethodes();
        classMethodes = new ClassMethodes();
        paymentMethodes = new PaymentMethodes();
        getClasses();
    }

    public void getClasses() {
        this.lessonList = classMethodes.getClasses();
    }

    public void fillCostTable(List<PaymentModel> paymentList) {
        int rowCount = this.tbPayments.getRowCount();
        int currentCount = 0;
        if (rowCount > 0) {
            for (int i = rowCount - 1; i > -1; i--) {
                modelSetTable.removeRow(i);
            }
        }
        tbPayments.setModel(modelSetTable);

        if (!this.columsAreSet) {
            modelSetTable.addColumn("Maand");
            modelSetTable.addColumn("Bedrag");
            modelSetTable.addColumn("Geregisteerd door:");
            this.columsAreSet = true;
        }

        for (PaymentModel paymentModel : paymentList) {
            Object[][] data = {new Object[]{paymentModel.getMonth(), paymentModel.getAmount(), paymentModel.getRegisterdBy()}};
            modelSetTable.addRow(data);
            modelSetTable.setValueAt(paymentModel.getMonth(), currentCount, 0);
            modelSetTable.setValueAt(paymentModel.getAmount(), currentCount, 1);
            modelSetTable.setValueAt(paymentModel.getRegisterdBy(), currentCount, 2);
            currentCount++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.s
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPayments = new javax.swing.JTable();
        cbClasses = new javax.swing.JComboBox<>();
        btGoBack = new javax.swing.JButton();
        btSafePayments = new javax.swing.JButton();
        lbStudentsCostPageTitle = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbStudent = new javax.swing.JLabel();
        cbStudents = new javax.swing.JComboBox<>();
        lbLastEditBy = new javax.swing.JLabel();
        lbStudent1 = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();

        tbPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbPayments);

        cbClasses.addItem("Selecteer een klas");

        for(Lesson les : this.lessonList){
            cbClasses.addItem(les.getClassName());
        }
        cbClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClassesActionPerformed(evt);
            }
        });

        btGoBack.setLabel("Vorige");
        btGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoBackActionPerformed(evt);
            }
        });

        btSafePayments.setText("Opslaan");
        btSafePayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSafePaymentsActionPerformed(evt);
            }
        });

        lbStudentsCostPageTitle.setText("KostenOverzicht Studenten");

        lbClass.setText("Klas:");

        lbStudent.setText("Student:");

        this.cbStudents.addItem("Selecteer een Student");

        for(Student student : this.studentList){
            cbStudents.addItem(student.getId() + ","+ student.getFirstName() + "," + student.getLastName());
        }
        cbStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStudentsActionPerformed(evt);
            }
        });

        lbLastEditBy.setText("Laatst aangepast door : ");

        lbStudent1.setText("Jaar:");

        this.cbYear.addItem("Selecteer een Jaar");
        String[] years = new String[]{"2018","2019","2020","2021","2022","2023","2024","2025"};

        for(String year : years){
            cbYear.addItem(year);

        }
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbClass)
                                .addComponent(lbStudent)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbClasses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btSafePayments)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lbStudentsCostPageTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lbLastEditBy, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btGoBack)
                    .addContainerGap(582, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbStudentsCostPageTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStudent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lbLastEditBy)
                .addGap(41, 41, 41)
                .addComponent(btSafePayments)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(btGoBack)
                    .addGap(33, 33, 33)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStudentsActionPerformed
        // TODO add your handling code here:
        String studentId = this.cbStudents.getSelectedItem().toString().split(",")[0];
        int[] months = new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
        List<PaymentModel> paymentResult = this.paymentMethodes.getMonthlyContribution(Integer.parseInt(studentId), months, 2012);

    }//GEN-LAST:event_cbStudentsActionPerformed

    private void btSafePaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSafePaymentsActionPerformed
        // TODO add your handling code here:
        int rowCount = this.modelSetTable.getRowCount();


    }//GEN-LAST:event_btSafePaymentsActionPerformed

    private void btGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoBackActionPerformed
        mainAppFrame main = new mainAppFrame();
        this.setVisible(false);

        main.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btGoBackActionPerformed

    private void cbClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClassesActionPerformed
        // TODO add your handling code here:
        String selectedClass = this.cbClasses.getSelectedItem().toString();
        if (!selectedClass.equalsIgnoreCase("Selecteer een klas")) {
            this.studentList = this.studentsMethodes.getStudentsFromClass(selectedClass);
        } else {
            this.studentList.clear();
        }
    }//GEN-LAST:event_cbClassesActionPerformed

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGoBack;
    private javax.swing.JButton btSafePayments;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JComboBox<String> cbStudents;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbLastEditBy;
    private javax.swing.JLabel lbStudent;
    private javax.swing.JLabel lbStudent1;
    private javax.swing.JLabel lbStudentsCostPageTitle;
    private javax.swing.JTable tbPayments;
    // End of variables declaration//GEN-END:variables
}
